# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 1012
    connection-timeout: 5000
    servlet:
        context-path: /base

spring:
    # 环境 dev|test|prod
    profiles:
        active: dev
    # jackson时间格式化
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    http:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
            enabled: true

    
#mybatis
mybatis:
    #实体类所在包位置
    type-aliases-package: com.example.base.entity
    #mapper.xml所在位置
    mapper-locations: classpath:mapper/*Mapper.xml


#日志
logging:
    config: classpath:log4j2-dev.xml


